//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WAProdocutos.WRGestionProductos {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGestionProductosSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    public partial class WSGestionProductos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wmListarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmCrearProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmActualizarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmEliminarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wmTrasladarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGestionProductos() {
            this.Url = global::WAProdocutos.Properties.Settings.Default.WAProdocutos_WRGestionProductos_WSGestionProductos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wmListarProductosCompletedEventHandler wmListarProductosCompleted;
        
        /// <remarks/>
        public event wmCrearProductoCompletedEventHandler wmCrearProductoCompleted;
        
        /// <remarks/>
        public event wmActualizarProductoCompletedEventHandler wmActualizarProductoCompleted;
        
        /// <remarks/>
        public event wmEliminarProductoCompletedEventHandler wmEliminarProductoCompleted;
        
        /// <remarks/>
        public event wmTrasladarProductoCompletedEventHandler wmTrasladarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmListarProductos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductosRPT wmListarProductos() {
            object[] results = this.Invoke("wmListarProductos", new object[0]);
            return ((ProductosRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmListarProductosAsync() {
            this.wmListarProductosAsync(null);
        }
        
        /// <remarks/>
        public void wmListarProductosAsync(object userState) {
            if ((this.wmListarProductosOperationCompleted == null)) {
                this.wmListarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmListarProductosOperationCompleted);
            }
            this.InvokeAsync("wmListarProductos", new object[0], this.wmListarProductosOperationCompleted, userState);
        }
        
        private void OnwmListarProductosOperationCompleted(object arg) {
            if ((this.wmListarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmListarProductosCompleted(this, new wmListarProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmCrearProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoInsertarRPT wmCrearProducto(ProductoInsertarRQT toProductoRequest) {
            object[] results = this.Invoke("wmCrearProducto", new object[] {
                        toProductoRequest});
            return ((ProductoInsertarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmCrearProductoAsync(ProductoInsertarRQT toProductoRequest) {
            this.wmCrearProductoAsync(toProductoRequest, null);
        }
        
        /// <remarks/>
        public void wmCrearProductoAsync(ProductoInsertarRQT toProductoRequest, object userState) {
            if ((this.wmCrearProductoOperationCompleted == null)) {
                this.wmCrearProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmCrearProductoOperationCompleted);
            }
            this.InvokeAsync("wmCrearProducto", new object[] {
                        toProductoRequest}, this.wmCrearProductoOperationCompleted, userState);
        }
        
        private void OnwmCrearProductoOperationCompleted(object arg) {
            if ((this.wmCrearProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmCrearProductoCompleted(this, new wmCrearProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmActualizarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoActualizarRPT wmActualizarProducto(ProductoActualizarRQT toProductoRequest) {
            object[] results = this.Invoke("wmActualizarProducto", new object[] {
                        toProductoRequest});
            return ((ProductoActualizarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmActualizarProductoAsync(ProductoActualizarRQT toProductoRequest) {
            this.wmActualizarProductoAsync(toProductoRequest, null);
        }
        
        /// <remarks/>
        public void wmActualizarProductoAsync(ProductoActualizarRQT toProductoRequest, object userState) {
            if ((this.wmActualizarProductoOperationCompleted == null)) {
                this.wmActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("wmActualizarProducto", new object[] {
                        toProductoRequest}, this.wmActualizarProductoOperationCompleted, userState);
        }
        
        private void OnwmActualizarProductoOperationCompleted(object arg) {
            if ((this.wmActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmActualizarProductoCompleted(this, new wmActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmEliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoEliminarRPT wmEliminarProducto(ProductoEliminarRQT toProductoEliminar) {
            object[] results = this.Invoke("wmEliminarProducto", new object[] {
                        toProductoEliminar});
            return ((ProductoEliminarRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmEliminarProductoAsync(ProductoEliminarRQT toProductoEliminar) {
            this.wmEliminarProductoAsync(toProductoEliminar, null);
        }
        
        /// <remarks/>
        public void wmEliminarProductoAsync(ProductoEliminarRQT toProductoEliminar, object userState) {
            if ((this.wmEliminarProductoOperationCompleted == null)) {
                this.wmEliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("wmEliminarProducto", new object[] {
                        toProductoEliminar}, this.wmEliminarProductoOperationCompleted, userState);
        }
        
        private void OnwmEliminarProductoOperationCompleted(object arg) {
            if ((this.wmEliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmEliminarProductoCompleted(this, new wmEliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wmTrasladarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoMoverRPT wmTrasladarProducto(ProMovTrasladoRQT toProducto) {
            object[] results = this.Invoke("wmTrasladarProducto", new object[] {
                        toProducto});
            return ((ProductoMoverRPT)(results[0]));
        }
        
        /// <remarks/>
        public void wmTrasladarProductoAsync(ProMovTrasladoRQT toProducto) {
            this.wmTrasladarProductoAsync(toProducto, null);
        }
        
        /// <remarks/>
        public void wmTrasladarProductoAsync(ProMovTrasladoRQT toProducto, object userState) {
            if ((this.wmTrasladarProductoOperationCompleted == null)) {
                this.wmTrasladarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwmTrasladarProductoOperationCompleted);
            }
            this.InvokeAsync("wmTrasladarProducto", new object[] {
                        toProducto}, this.wmTrasladarProductoOperationCompleted, userState);
        }
        
        private void OnwmTrasladarProductoOperationCompleted(object arg) {
            if ((this.wmTrasladarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wmTrasladarProductoCompleted(this, new wmTrasladarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductosRPT : Error {
        
        private ProductoCN[] paProductosField;
        
        /// <remarks/>
        public ProductoCN[] paProductos {
            get {
                return this.paProductosField;
            }
            set {
                this.paProductosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoCN {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoMoverRPT {
        
        private string pcCodigoField;
        
        private string pcMensajeField;
        
        private string pcNomProField;
        
        private int pnIdeOriField;
        
        private int pnIdeDesField;
        
        private int pnCanMovField;
        
        /// <remarks/>
        public string pcCodigo {
            get {
                return this.pcCodigoField;
            }
            set {
                this.pcCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string pcMensaje {
            get {
                return this.pcMensajeField;
            }
            set {
                this.pcMensajeField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeOri {
            get {
                return this.pnIdeOriField;
            }
            set {
                this.pnIdeOriField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeDes {
            get {
                return this.pnIdeDesField;
            }
            set {
                this.pnIdeDesField = value;
            }
        }
        
        /// <remarks/>
        public int pnCanMov {
            get {
                return this.pnCanMovField;
            }
            set {
                this.pnCanMovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProMovTrasladoRQT {
        
        private string cNomProField;
        
        private int nIdeOriField;
        
        private int nIdeDesField;
        
        private int nCanMovField;
        
        /// <remarks/>
        public string cNomPro {
            get {
                return this.cNomProField;
            }
            set {
                this.cNomProField = value;
            }
        }
        
        /// <remarks/>
        public int nIdeOri {
            get {
                return this.nIdeOriField;
            }
            set {
                this.nIdeOriField = value;
            }
        }
        
        /// <remarks/>
        public int nIdeDes {
            get {
                return this.nIdeDesField;
            }
            set {
                this.nIdeDesField = value;
            }
        }
        
        /// <remarks/>
        public int nCanMov {
            get {
                return this.nCanMovField;
            }
            set {
                this.nCanMovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoEliminarRQT {
        
        private int pnIdeProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRQT {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoInsertarRQT {
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoEliminarRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoActualizarRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductoInsertarRPT))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductosRPT))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error {
        
        private string pcCodigoField;
        
        private string pcMensajeField;
        
        /// <remarks/>
        public string pcCodigo {
            get {
                return this.pcCodigoField;
            }
            set {
                this.pcCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string pcMensaje {
            get {
                return this.pcMensajeField;
            }
            set {
                this.pcMensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoEliminarRPT : Error {
        
        private int pnIdeProField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoActualizarRPT : Error {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoInsertarRPT : Error {
        
        private int pnIdeProField;
        
        private string pcNomProField;
        
        private string pcDesProField;
        
        private decimal pnPreProField;
        
        private int pnStoProField;
        
        private System.DateTime ptFecProField;
        
        private int pnIdeSedField;
        
        /// <remarks/>
        public int pnIdePro {
            get {
                return this.pnIdeProField;
            }
            set {
                this.pnIdeProField = value;
            }
        }
        
        /// <remarks/>
        public string pcNomPro {
            get {
                return this.pcNomProField;
            }
            set {
                this.pcNomProField = value;
            }
        }
        
        /// <remarks/>
        public string pcDesPro {
            get {
                return this.pcDesProField;
            }
            set {
                this.pcDesProField = value;
            }
        }
        
        /// <remarks/>
        public decimal pnPrePro {
            get {
                return this.pnPreProField;
            }
            set {
                this.pnPreProField = value;
            }
        }
        
        /// <remarks/>
        public int pnStoPro {
            get {
                return this.pnStoProField;
            }
            set {
                this.pnStoProField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ptFecPro {
            get {
                return this.ptFecProField;
            }
            set {
                this.ptFecProField = value;
            }
        }
        
        /// <remarks/>
        public int pnIdeSed {
            get {
                return this.pnIdeSedField;
            }
            set {
                this.pnIdeSedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wmListarProductosCompletedEventHandler(object sender, wmListarProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmListarProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmListarProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductosRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductosRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wmCrearProductoCompletedEventHandler(object sender, wmCrearProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmCrearProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmCrearProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoInsertarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoInsertarRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wmActualizarProductoCompletedEventHandler(object sender, wmActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoActualizarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoActualizarRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wmEliminarProductoCompletedEventHandler(object sender, wmEliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmEliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmEliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoEliminarRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoEliminarRPT)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wmTrasladarProductoCompletedEventHandler(object sender, wmTrasladarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wmTrasladarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wmTrasladarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoMoverRPT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoMoverRPT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591